# Booster T1 Robot - Constrained Position Control Configuration
#
# This configuration file defines ROS2 controllers for the Booster T1 robot
# using native ROS2 topic communication with constrained position control.
# The hardware interface communicates with the robot via /joint_ctrl and /joint_state topics.
#
# Controllers:
# - joint_state_broadcaster: Publishes joint states to /joint_states
# - constrained_position_controller: Constrained control with velocity, acceleration, and jerk limits
#
# The ConstrainedPositionController uses Ruckig trajectory generation for smooth
# motion planning with configurable constraints for each joint.
#
# Usage: Used by booster_constrained_control.launch.py

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz - Control loop frequency

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    constrained_position_controller:
      type: aatb_controllers/ConstrainedPositionController

joint_state_broadcaster:
  ros__parameters:
    # Uses hardware interface joint discovery order - no explicit joint list needed
    publish_rate: 50.0

constrained_position_controller:
  ros__parameters:
    joints:
      - Head_yaw
      - Head_pitch
      - Left_Shoulder_Pitch
      - Left_Shoulder_Roll
      - Left_Elbow_Pitch
      - Left_Shoulder_Yaw
      - Right_Shoulder_Pitch
      - Right_Shoulder_Roll
      - Right_Elbow_Pitch
      - Right_Shoulder_Yaw
      - Waist
      - Left_Hip_Pitch
      - Left_Hip_Roll
      - Left_Hip_Yaw
      - Left_Knee_Pitch
      - Left_Ankle_Pitch
      - Left_Ankle_Roll
      - Right_Hip_Pitch
      - Right_Hip_Roll
      - Right_Hip_Yaw
      - Right_Knee_Pitch
      - Right_Ankle_Pitch
      - Right_Ankle_Roll
    interface_name: position
    state_interfaces:
      - position
      - velocity
    # Motion constraints per joint (23 joints total for T1)
    velocity_limits: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]       # rad/s
    acceleration_limits: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]   # rad/s²
    jerk_limits: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0] # rad/s³

    # Control cycle time (should match controller_manager update_rate)
    control_cycle_time: 0.01  # seconds (100 Hz)